### ISSUE TITLE
Reads and megahit

### ISSUE THREAD

**Issue by lurens** [MayroseLab/Panoramic#16]
Hi
I have a couple of questions on your pipeline:
1) It is not clear to me how use my own reads, instead of downloading from ENA. I tried the test run pipeline but ENA is not responding. So I would like to download them and use directly for the test run. Useful also for using my data
2) How I set megahit parameters: Should I edit the configuration.yml file or do  I have to set them directly in the genome_assembly.snakefile?
3) Would it be possible to skip trimmomatic step (If I already have my trimmed reads)?
Thanks

**Comment by soungalo** [comment]
Hi there,
I am working on ways to make the pipeline more flexible, so you can insert your data at any point more easily. This will be implemented in the next release. Meanwhile:
1. You will have to create a directory structure and place your files there for each sample like that:
```
<output dir>/per_sample/<sample name>/data/<ena ref>_1.fastq.gz
<output dir>/per_sample/<sample name>/data/<ena ref>_2.fastq.gz
```

2. I did not externalize the assembler parameters (will have to think of a way to do that), so you'll have to modify the snakefile. What parameters do you want to set?

3. Similar to 1, you will have to create:
```
<output dir>/per_sample/<sample name>/RPP_<ena ref>/<ena ref>_1_clean_paired.fastq.gz
<output dir>/per_sample/<sample name>/RPP_<ena ref>/<ena ref>_1_clean_unpaired.fastq.gz
<output dir>/per_sample/<sample name>/RPP_<ena ref>/<ena ref>_2_clean_paired.fastq.gz
<output dir>/per_sample/<sample name>/RPP_<ena ref>/<ena ref>_2_clean_unpaired.fastq.gz
```

Sorry for the inconvenience - I hope to improve it soon. LMK how it works.
Also, can you explain what you mean by "ENA is not responding"? Any error messages?

**Comment by lurens** [comment]
Thank you for the reply.
Concerning megahit parameters, I would like to set for example the Kmers to test, or set some other parameters like --cleaning-rounds 1 --disconnect-ratio 0

3) Still have this error message:
File "/home/Gen6_8TB/Test_panoramic/Panoramic/test/map_to_pan/RESULT/ena-fast-download.py", line 115, in <module>
    subprocess.check_call(cmd,shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'ascp -T -l 300m -P33001  -i ./.snakemake/conda/759d6ce9/etc/asperaweb_id_dsa.openssh era-fasp@fasp.sra.ebi.ac.uk:/vol1/fastq/ERR130/006/ERR1309526/ERR1309526_1.fastq.gz /home/Gen6_8TB/Test_panoramic/Panoramic/test/map_to_pan/RESULT/per_sample/T73-1b/data' returned non-zero exit status 1

**Comment by soungalo** [comment]
Can you please attach the snakemake log as well as the rule-specific logs:
```
.../RESULT/logs/T73-1b_download_fastq.out
.../RESULT/logs/T73-1b_download_fastq.err
```

**Comment by lurens** [comment]
I can upload the error log and the out file
As you can see, ENA is not responding for downloading. Got the same issue with wget.
But i can  download reads from ENA site (not ftp).
.-) ../RESULT/logs/ is an empty directory

[out.txt](https://github.com/MayroseLab/Panoramic/files/5944003/out.txt)
[err.txt](https://github.com/MayroseLab/Panoramic/files/5944004/err.txt)

**Comment by soungalo** [comment]
Hmmm, it seems like ena-fast-download.py is able to connect to ENA, fetch the right FTP, and run the right ascp command, but for some reason it fails to download. Would you mind trying the following:
```
conda activate ./.snakemake/conda/759d6ce9/
ascp -T -l 300m -P33001  -i ./.snakemake/conda/759d6ce9/etc/asperaweb_id_dsa.openssh era-fasp@fasp.sra.ebi.ac.uk:/vol1/fastq/ERR130/007/ERR1309477/ERR1309477_1.fastq.gz /home/Gen6_8TB/Test_panoramic/Panoramic/test/map_to_pan/RESULT/per_sample/OS-1118/data
```
(or use full paths)
LMK what happens.

**Comment by lurens** [comment]
Yep, no connection.
Session Stop  (Error: Client unable to connect to server (check UDP port and firewall))

**Comment by soungalo** [comment]
Sorry, but I don't know how to help with that. Might be related to security settings or software on your machine. You'll probably need to ask for help from your sys admin or from the Aspera support.

**Comment by lurens** [comment]
Ok
Anyway, it seems to run with reads downloaded directly from ena site.
Thanks

**Comment by soungalo** [comment]
OK, so I'm closing this issue for now. Feel free to update/reopen if anything comes up.
