### ISSUE TITLE
Replace ena_fast_download.py with Kingfisher

### ISSUE THREAD

**Issue by soungalo** [MayroseLab/Panoramic#17]
If possible, use a conda env instead of having a rule to download the software.

**Comment by zhuofeih** [comment]
Hi Soungalo,

I am using Panoramic latest version 1.1.0 (released in Jan 2021). Now I am facing an issue. The pipeline stopped when snakemake ran the rule "fetch_ena_fast_download_script". In this rule, snakemake runs:

wget https://raw.githubusercontent.com/wwood/ena-fast-download/master/ena-fast-download.py -O /scratch/gacrc-test/Panoramic_workdir/test/map_to_pan/RESULT/ena-fast-download.py

to download ena-fast-download.py into the RESULT folder in its working space. When I ran wget directly:

wget https://raw.githubusercontent.com/wwood/ena-fast-download/master/ena-fast-download.py

I got ERROR 404: Not Found. The download address is not available anymore. I found your post here. I have two questions:

How to integrate Kingfisher into Panoramic pipeline via snakemake file?
Have you corrected this issue in a new version of Panoramic? 

Thanks so much for your time and help!

Best,
Zhuofei

**Comment by soungalo** [comment]
Hi, sorry about that. I am working on a new release (hopefully will be done in a few weeks) where ena_fast_download.py will be replaced by kingfisher, as the script is no longer available to download. For now, just download the script from here and put it in the RESULT dir (remove the .txt suffix).
[ena-fast-download.py.txt](https://github.com/MayroseLab/Panoramic/files/9665353/ena-fast-download.py.txt)

**Comment by zhuofeih** [comment]
Hi Soungalo, Thanks so much for this file! Hopefully we can get a new version where ena_fast_download.py is replaced by kingfisher soon! 
Best,
Zhuofei

**Comment by zhuofeih** [comment]
Hi Soungalo,

I tested test/map_to_pan using snakemake/5.7.1. It works fine.
However, when I did the same test using snakemake/6.3.0, it seems that the following line in PGC_map_to_pan.snakefile:

include: "../genome_assembly/genome_assembly.snakefile"

caused an issue. In the **rule iterative_map_to_pan_HQ**, the variable pipeline_dir will be reassigned to /home/gacrc-test/Panoramic/genome_assembly , which is not right for iterative_map_to_pan.py script (it is in map_to_pan/, not in genome_assembly/). It seem that the behavior of "include" is changed in snakemake/6.3.0 . 
Just let you know this. Thanks!

**Comment by soungalo** [comment]
Thanks, I'll make sure the next release is compatible with the latest snakemake version.

**Comment by zhuofeih** [comment]
Thank you so much!

**Comment by soungalo** [comment]
Replaced in commit 9d0b0fadcd5df263b484eabe6260cd95ce0e0611 (currently in branch v1.2 - will be merged later).

**Comment by soungalo** [comment]
Fixed in v1.2.0.
